### ISSUE TITLE
Change default behaviour of --accumulators and --memory-cells when --disable-memory-detection is set

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#31]
While --disable-memory-detection is set, --accumulators and --memory-cells are currently both mandatory. 
This should no longer be the case. 
Instead, if omitted, zero accumulators / no (named) memory cells should be assumed. 

Note that the requested change should only influence the behavior in combination with --disable-memory-detection.

**Comment by LMH01** [comment]
I will take a look, related to #30

**Comment by LMH01** [comment]
implemented
