### ISSUE TITLE
Change hotkeys

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#32]
Change the following (hotkeys and description):
- Run [r] -> Start [s]
- Run to end [n] -> Run to end [r]
- Run next instruction [r] -> Run next instruction [n]
- Reset [s] -> Reset [t]
- Toggle breakpoint [t] -> Toggle breakpoint [b]

**Comment by LMH01** [comment]
I will change it, when I have some time

**Comment by LMH01** [comment]
completed and will be included in the next release
