### ISSUE TITLE
Make "Execution finished!" window less wide

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#46]
In "Load"-Mode, the "Execution finished!" window should be less wide such that the content of the memory cells section to the right is still fully visible

**Comment by LMH01** [comment]
Should be easily doable, the implementation on how the `run custom instruction` popup is drawn is quite similar i'd say.

We however will have to be careful with line wrap, that everything is still visible, when the window is resized below a certain width.

**Comment by LMH01** [comment]
implemented
