### ISSUE TITLE
Add `autodetection` support for memory config file

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#62]
Each type of memory should support the optional field `autodetection` in memory config files. If set to true or false, autodetection (i.e. not specified accumulators/memory cells/index memory cells get created on the fly if they are used) is actived or not activated. If not set, the "default" behavior applies -> autodetection is enabled, unless `--disable-auto-detection` is given.  

It probably makes sence that, if set, the options in the memory config file take prevalence over `--disable-auto-detection`. Or maybe `--memory-config-file` should even conflict with `--disable-auto-detection`?  
  
This behavior needs to be documented.  

---
  
It might be helpful to first do some refactoring (see #61).  
This feature might fit well into the `Settings` of the runtime.  
  
A good way of implementation may be to have four variables for the four types of memory, that store whether autodetection (i.e. more memorycells/accumulators/... can be used and are created when used, than what is defined in the memory layout file) is enabled.
Parsing goes as follows:
1. Set all four variables to `true`
2. If `--disable-memory-detection` is given, set all four variables to `false`
3. For each of the four variables where the corresponding entry in the memory layout json is given, set it to the given value.
With this Implementation, everywhere in the code only the four boolean variables should be referenced and never whether `--disable-memory-detection` is given anymore.

## TODO
- [x] Update documentation

**Comment by LMH01** [comment]
Good ideas, I will try to implement it.

**Comment by LMH01** [comment]
> Or maybe --memory-config-file should even conflict with --disable-auto-detection?

I'm not sure about that one, I will have to think about that.

**Comment by LMH01** [comment]
> --memory-config-file should even conflict with --disable-auto-detection

I thought about it and I don't think that this is a good idea. The implementation I have implemented also works when booth values are set.

**Comment by LMH01** [comment]
The base behavior has been implemented, the docs and the changelog will have to be updated.

**Comment by LMH01** [comment]
Changelog and docs have been updated, when @reeelix has taken a look if the implementation is fitting, this issue can be closed.

**Comment by LMH01** [comment]
We spoke and the feature seems to be implemented correctly.
