### ISSUE TITLE
insufficient instruction checking in `run custom instruction` dialog

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#63]
Some instructions that should not be allowed in the given setup (i.e. that are blocked if contained in a given program) are not blocked when run via the `run custom instruction` dialog. Two examples are using the gamma register when it is disabled, and using `push`/`pop`.  
  
Previously to fixing this, some refactoring may be necessary (see #61).  
  
Restrictions on the used instructions can be stored well in the `Settings` of the runtime. Then, code from `RuntimeBuilder::check_instructions` can be used (maybe this function should be refactored or moved somewhere else) when building custom instructions in `fn custom_instruction_enter` in `app/mod.rs`.

**Comment by LMH01** [comment]
I will try to fix that.

**Comment by LMH01** [comment]
this has been fixed and will be included in the next release
