### ISSUE TITLE
Treat `y` as normal memory cell, if gamma accumulator is disabled

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#64]
If `--disable-memory-detection` is set, and `--enable-gamma-accumulator true` is not set, then `y` should be treated like a normal memory cell (i.e. it should work if it is given with `--memory-cells y`).  
Right now, trying to use `p(y) := const` results in the following error:  
```
Error: runtime_build_error::gamma_disabled

  × while building runtime
  ╰─▶ Gamma accumulator is used in the program but is disabled
  help: You can't use the gamma accumulator when it is disabled, to enable it you can either enable automatic
        memory detection
        by removing the "--disable-memory-detection" flag or you can explicitly enable it by using the
        "--enable-gamma-accumulator" flag.
```

This would be kinda important for the way that memory cells are named sometimes in the lecture. 

TODO
- [ ] Write tests
- [ ] Fix problem with --disable-memory-detection and -m MEMORY_CELLS

**Comment by LMH01** [comment]
I don't know If I'm able to do it easily, as some parsing depends on the way gamma is currently implemented. I will see if I can get it to work, but it could take some time.

**Comment by LMH01** [comment]
I just double checked: To make it work like you described, some parsing would have to be rewritten and the parsing function would require a parameter that states if gamma should be active or not. This would break many things and I think the implementation would become quite ugly.

Maybe an alternative would be to rename gamma to some other symbol? What do you think?

**Comment by LMH01** [comment]
This has been implemented, but I have to write some tests, to test if it works properly.

**Comment by LMH01** [comment]
Seems I forgot a case: When p(y) is used and the following command is run

```
--disable-memory-detection -m MEMORY_CELLS
```

The result is the following output:

```
Building instructions
Building runtime
Error: runtime_build_error::gamma_disabled

  × Gamma accumulator is used in the program but is disabled
  help: You can't use the gamma accumulator when it is disabled, to enable it you can either enable automatic memory detection
        by removing the "--disable-memory-detection" flag or you can explicitly enable it by using the "--enable-gamma-accumulator" flag.
```

**Comment by LMH01** [comment]
bug has been fixed and another test has been added, feature is ready
