### ISSUE TITLE
From `Playground` mode, remove `--accumulators`, `--memory-cells` and `--index-memory-cells`

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#70]
Those options don't really make to much sense in playground mode, as there is no `--disable-memory-detection` flag in playground mode.  
Therefore, all the flags `--accumulators`, `--memory-cells` and `--index-memory-cells` do is to put some memory cells/accumulators/index memory cells into the listings initially, even before their first use. This is not important in playground mode, as it is meant only for trying things around. The request is in compliance with how `--enable-gamma-accumulator` is handled, as it already isn't available in playground mode for exactly the aforementioned reasons.  
  
Restrictions that apply in playground mode (if such should be possible) can then still be used using memory config files (after #62 is implemented), if one reeally wants them.

**Comment by reeelix** [comment]
not urgent

**Comment by LMH01** [comment]
Removing these values would require them to be moved into another argument group, but that *should* not be too difficult. I don't know however when I will be able to implement it.

**Comment by LMH01** [comment]
implemented and will be included in next release
