### ISSUE TITLE
Remove lines starting with `#` from view

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#73]
In programs, you sometimes want to give a little preamble with some information. This only makes the view of the program quite cluttered in alpha_tui. Therefore, a way to make comments that don't appear in alpha_tui would be beneficial.  
I propose that `//` keep their normal behaviour and `#` commands get the new behaviour lines starting with them are not shown (lines where they appear not at the start should still be shown)

**Comment by LMH01** [comment]
Good idea, the implementation shouldn't be too hard either. The documenation should then be updated to reflect this change.

**Comment by LMH01** [comment]
This has been implemented and will be included in the next release.
