### ISSUE TITLE
Breakpoints not scrolling correctly when the view is jumping on exiting debug mode

### ISSUE THREAD

**Issue by reeelix** [LMH01/alpha_tui#79]
When setting breakpoints in debug mode and the view is scrolled differently than before during debug mode, the breakpoints in the left column don't get moved to their correct positions when leaving debug mode (where the rest of the view jumps back to how it was before entering debug mode)

**Comment by LMH01** [comment]
Thanks for reporting that, I will take a look when I have some time.

**Comment by LMH01** [comment]
Should be fixed now. Will be included in next release.
